// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cv-landing/BoldVibrant.tsx": () => import("../components/mockups/cv-landing/BoldVibrant.tsx"),
  "./components/mockups/cv-landing/LuxuryPremium.tsx": () => import("../components/mockups/cv-landing/LuxuryPremium.tsx")
};
